// Token types for QLang lexer
let TokenKind = {};
TokenKind.Number = "Number";
TokenKind.String = "String";
TokenKind.True = "True";
TokenKind.False = "False";
TokenKind.Identifier = "Identifier";
TokenKind.Let = "Let";
TokenKind.If = "If";
TokenKind.Else = "Else";
TokenKind.While = "While";
TokenKind.Return = "Return";
TokenKind.Import = "Import";
TokenKind.Export = "Export";
TokenKind.Null = "Null";
TokenKind.Plus = "Plus";
TokenKind.Minus = "Minus";
TokenKind.Star = "Star";
TokenKind.Slash = "Slash";
TokenKind.Percent = "Percent";
TokenKind.Bang = "Bang";
TokenKind.BitwiseXor = "BitwiseXor";
TokenKind.Arrow = "Arrow";
TokenKind.EqualEqual = "EqualEqual";
TokenKind.NotEqual = "NotEqual";
TokenKind.Equal = "Equal";
TokenKind.LessEqual = "LessEqual";
TokenKind.GreaterEqual = "GreaterEqual";
TokenKind.Less = "Less";
TokenKind.Greater = "Greater";
TokenKind.And = "And";
TokenKind.BitwiseAnd = "BitwiseAnd";
TokenKind.Or = "Or";
TokenKind.BitwiseOr = "BitwiseOr";
TokenKind.LeftParen = "LeftParen";
TokenKind.RightParen = "RightParen";
TokenKind.LeftBrace = "LeftBrace";
TokenKind.RightBrace = "RightBrace";
TokenKind.LeftBracket = "LeftBracket";
TokenKind.RightBracket = "RightBracket";
TokenKind.Comma = "Comma";
TokenKind.Dot = "Dot";
TokenKind.Semicolon = "Semicolon";
TokenKind.Colon = "Colon";
TokenKind.Question = "Question";
TokenKind.QuestionQuestion = "QuestionQuestion";
TokenKind.Newline = "Newline";
TokenKind.Eof = "Eof";
TokenKind.Error = "Error";

// Keyword map for lexer
let kwMap = {};
kwMap["let"] = TokenKind.Let;
kwMap["if"] = TokenKind.If;
kwMap["else"] = TokenKind.Else;
kwMap["while"] = TokenKind.While;
kwMap["return"] = TokenKind.Return;
kwMap["true"] = TokenKind.True;
kwMap["false"] = TokenKind.False;
kwMap["import"] = TokenKind.Import;
kwMap["export"] = TokenKind.Export;
kwMap["null"] = TokenKind.Null;

export TokenKind;
export kwMap;
