let o = { a: 1, b: 2 };
println(o.a);
println(o.b);
o.a = 5;
println(o.a);
let p = o;
o.b = 7;
println(p.b);
let s = "abc";
println(s.length);
let a = [1, 2, 3];
println(a.length);
a.add(4);
println(a.length);
println(a[3]);
a.remove(0);
println(a[0]);
println(a.length);
let o2 = { length: 5 };
println(o2.length);
let c = [[1, 2], [3, 4]];
println(c[1][0]);
